apiVersion: v1
kind: Service
metadata:
  name: cfe-nginx-service
spec:
  selector:
    app: cfe-nginx-deployment
  type: LoadBalancer # external IP
  ports:
    - protocol: TCP
      port: 80 # http -> 80
      targetPort: cfe-nginx-port
